name: sameple ci
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
    - name: disk space
      run: df
    - name: env var
      run: env
    - name: mvn
      run: mvn -v
    - name: docker
      run: docker version
    - name: git clone
      uses: actions/checkout@v2
    - name: find all
      run: ls -a
    - name: os
      run: cat /etc/os-release
    - run: gradle -v
  
